Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.define "docker-lab" do |lab_d42|
    lab_d42.vm.box = "ubuntu/xenial64"
    lab_d42.vm.hostname = "docker-lab"
    lab_d42.vm.network :private_network, ip: "10.10.10.42"

    lab_d42.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbooks/bootstrap_python.yml"
    end
  end

end
