version: '3.4'

services:
  mongodb:
    image: mongo:3.4
    volumes:
      - vol_mongo_db:/data/db
    networks:
      net_search:
        aliases:
          - se_mongo_ui_db
          - se_mongo_crawler_db
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3.7
    environment:
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
      RABBITMQ_DEFAULT_USER: ${RMQ_USERNAME}
    networks:
      net_search:
        aliases:
          - se_rabbit
    ports:
      - "15672:15672"
      - "5672:5672"

  crawler:
    build: ./search_engine_crawler
    image: ${USERNAME}/se_crawler:${UI_VERSION}
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      MONGO: se_mongo_crawler_db
      MONGO_PORT: 27017
      RMQ_HOST: se_rabbit
      RMQ_QUEUE: ${RMQ_QUEUE}
      RMQ_USERNAME: ${RMQ_USERNAME}
      RMQ_PASSWORD: ${RMQ_PASSWORD}
      CHECK_INTERVAL: ${CRAWLER_CHECK_INTERVAL}
      EXCLUDE_URLS: ${CRAWLER_EXCLUDE_URLS}
      URL: ${CRAWLER_URL}
    networks:
      - net_search

  ui:
    build: ./search_engine_ui
    image: ${USERNAME}/se_ui:${UI_VERSION}
    environment:
      MONGO: se_mongo_ui_db
      MONGO_PORT: 27017
    ports:
      - ${UI_PORT}:${UI_PORT}/tcp
    networks:
      - net_search

volumes:
  vol_mongo_db:
    name: ${VOLUME_MONGO_DB}

networks:
  net_search:
    driver: bridge
